# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pull Request Checker

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  PR-Checker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          package:
            - 'pykg2tbl/**'
          tests:
            - 'tests/**'

    - name: Set up Python 3.8
      uses: actions/setup-python@v4.6.0
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make init-dev
        pip install -e .[tests]

    - name: Linting check
      id: linting_check
      if: ${{steps.filter.outputs.package == 'true' }} or ${{steps.filter.outputs.tests == 'true' }} 
      run: |
        make check

    - name: Test with pytest
      id: pytest_test
      if: ${{steps.filter.outputs.package == 'true' }} or ${{steps.filter.outputs.tests == 'true' }} 
      run: |
        make test

    - id: run-tests
      if: ${{steps.pytest_test.outcome == 'success'}}
      uses: dima-engineer/pytest-reporter@v2.1.1
      with:
        cov-omit-list: tests/*, *__init__*, *__version__*, *__main__*, *exceptions*
        cov-threshold-single: 85
        cov-threshold-total: 90
        async-tests: true
